services:
  backend:
    container_name: backend
    build: ./backend
    tty: true
    ports:
        - "8080:8080"
    volumes:
        - type: bind
          source: ./backend
          target: /go/src/app

  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    working_dir: /app
    volumes:
      - ./frontend:/app
      - node_modules:/app/node_modules
    environment:
      TZ: Asia/Tokyo
    tty: true

volumes:
  node_modules: