services:
  backend:
    container_name: backend
    build: ./backend
    tty: true
    ports:
        - "8080:8080"
    volumes:
        - type: bind
          source: ./backend
          target: /go/src/app