services:
  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: dev
    tty: true
    ports:
        - ${BACKEND_PORT:-8080}:8080
    volumes:
        - type: bind
          source: ./backend
          target: /go/src/app
    environment:
      TZ: Asia/Tokyo
      ENV: ${ENV}

  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: dev
    working_dir: /app
    tty: true
    ports:
        - ${FRONTEND_PORT:-3000}:3000
    volumes:
      - ./frontend:/app
      - node_modules:/app/node_modules
    environment:
      TZ: Asia/Tokyo
      BACKEND_ENDPOINT_URL: ${BACKEND_ENDPOINT_URL:-http://localhost:8080}
      ENV: ${ENV}
      VITE_GITHUB_URL: ${VITE_GITHUB_URL}
      VITE_X_URL: ${VITE_X_URL}
      VITE_GMAIL_ADDRESS: ${VITE_GMAIL_ADDRESS}
      VITE_IR_BANK_URL: ${VITE_IR_BANK_URL}

volumes:
  node_modules: